name: lincs-scgpt
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9.12
  - pytorch=1.13
  - pytorch-cuda=11.6
  - torchtext=0.14.0
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.13.1
  - scikit-learn=1.6.1
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - anndata=0.10.8
  - scanpy=1.10.3
  - h5py=3.11.0
  - tqdm
  - rdkit=2023.09.6
  - faiss-gpu
  - pip
  - pip:
      - scgpt==0.2.1
      - "flash-attn<1.0.5"
      - wandb
      - markupsafe==2.0.1
      - cmapPy
